#!/bin/bash

pepe=../pepe/pepe-launcher
conf=flat
nnodes=
cmd=/bin/bash

usage ()
{
    echo "launch [-n nnodes] [-c config]" >&2
    exit 1
}

while getopts "?hn:c:" opt; do
    case ${opt} in
        h|\?) usage ;;
        n) nnodes=${OPTARG} ;;
        c) conf=${OPTARG} ;;
    esac
done
confpath="./pepe/${conf}.lua"
test -f "$confpath" || usage

ulimit -c unlimited

if [ -n "$SLURM_NNODES" ]; then
    export LD_LIBRARY_PATH=/g/g0/dahn/workspace/FLUX-wreck-rebase/ngrm/zmq-broker/lib:${LD_LIBRARY_PATH}
    source /etc/profile.d/modules.sh
    module load mvapich2-gnu-psm
    srun --propagate=CORE -N${nnodes:-$SLURM_NNODES} --pty $pepe -c $confpath $cmd
else 
    test -n "$nnodes" || usage
    salloc -N$nnodes srun --propagate=CORE -N$nnodes --pty $pepe -c $confpath $cmd
fi


# vi:tabstop=4 shiftwidth=4 expandtab
