#!/bin/bash

while getopts "g" opt; do
    case ${opt} in
        \?) break;;
        g) CMDPREFIX="gdb -ex run --args";;
    esac
done


${CMDPREFIX} ./cmbd \
  --verbose \
  --rank=0 --size=1 \
  --plugins=modctl,api,barrier,kvs,log,job,rexec,sched \
  kvs:conf.log.reduction-timeout-msec=100 \
  kvs:conf.log.circular-buffer-entries=100000 \
  kvs:conf.log.persist-level=debug \
  sched:rdl-conf=conf/hype.lua
